In [1]:
import tensorflow as tf

In [9]:
dataset = tf.data.Dataset.range(10)

print([val.numpy() for val in dataset])
type(dataset)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


tensorflow.python.data.ops.dataset_ops.RangeDataset

In [31]:
dataset = tf.data.Dataset.range(10).window(size=5, shift=1)

print(type(dataset))
for pt in dataset:
    print([x.numpy() for x in pt])
print(type(pt))

<class 'tensorflow.python.data.ops.dataset_ops.WindowDataset'>
[0, 1, 2, 3, 4]
[1, 2, 3, 4, 5]
[2, 3, 4, 5, 6]
[3, 4, 5, 6, 7]
[4, 5, 6, 7, 8]
[5, 6, 7, 8, 9]
[6, 7, 8, 9]
[7, 8, 9]
[8, 9]
[9]
<class 'tensorflow.python.data.ops.dataset_ops._VariantDataset'>


In [32]:
dataset = tf.data.Dataset.range(10).window(size=5, shift=1, drop_remainder=True)

print(type(dataset))
for pt in dataset:
    print([x.numpy() for x in pt])
print(type(pt))

<class 'tensorflow.python.data.ops.dataset_ops.WindowDataset'>
[0, 1, 2, 3, 4]
[1, 2, 3, 4, 5]
[2, 3, 4, 5, 6]
[3, 4, 5, 6, 7]
[4, 5, 6, 7, 8]
[5, 6, 7, 8, 9]
<class 'tensorflow.python.data.ops.dataset_ops._VariantDataset'>


In [8]:
type(dataset)

tensorflow.python.data.ops.dataset_ops.WindowDataset

In [29]:
dataset = tf.data.Dataset.range(10).window(size=5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda w: w.batch(5))

print(type(dataset))
for pt in dataset:
    print(pt.numpy())
print(type(pt))

<class 'tensorflow.python.data.ops.dataset_ops.FlatMapDataset'>
[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [37]:
dataset = tf.data.Dataset.range(10).window(size=5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda w: w.batch(5))
dataset = dataset.map(lambda w: (w[:-1], w[-1]))

print(type(dataset))
for x, y in dataset:
    print(f'x={x.numpy()}, y={y.numpy()}')
print(type(x))
print(type(y))

<class 'tensorflow.python.data.ops.dataset_ops.MapDataset'>
x=[0 1 2 3], y=4
x=[1 2 3 4], y=5
x=[2 3 4 5], y=6
x=[3 4 5 6], y=7
x=[4 5 6 7], y=8
x=[5 6 7 8], y=9
<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [38]:
dataset = dataset.shuffle(buffer_size=10)

print(type(dataset))
for x, y in dataset:
    print(f'x={x.numpy()}, y={y.numpy()}')

<class 'tensorflow.python.data.ops.dataset_ops.ShuffleDataset'>
x=[5 6 7 8], y=9
x=[0 1 2 3], y=4
x=[1 2 3 4], y=5
x=[4 5 6 7], y=8
x=[2 3 4 5], y=6
x=[3 4 5 6], y=7


In [39]:
dataset = dataset.batch(2).prefetch(1)

print(type(dataset))
for x, y in dataset:
    print(f'x={x.numpy()}, y={y.numpy()}')

<class 'tensorflow.python.data.ops.dataset_ops.PrefetchDataset'>
x=[[3 4 5 6]
 [1 2 3 4]], y=[7 5]
x=[[0 1 2 3]
 [4 5 6 7]], y=[4 8]
x=[[2 3 4 5]
 [5 6 7 8]], y=[6 9]
